language: node_js
node_js:
  - "6"
  - "5"

before_install:
  - npm install -g typescript@1.8 typings@1.3

script:
  - typings install
  - npm test

after_success:
  - npm run coverage && codecov -f coverage/*.json
  - bash <(curl -s https://codecov.io/bash)
